### ISSUE TITLE
Failing tests in clean chroot package build

### ISSUE THREAD

**Issue by dvzrv** [sarugaku/pythonfinder#116]
Hi! When attempting to build this project in version 1.2.9 I also tried to run its tests.

Two unfortunately fail: `test_shims_are_kept` and `test_shims_are_removed`
Both seem to rely on git doing something, which is not possible in a clean chroot environment when building the project and running the tests afterwards.

Full build log: 
[pythonfinder-1.2.9-build.log](https://github.com/sarugaku/pythonfinder/files/7921118/pythonfinder-1.2.9-build.log)

Would it be possible to hide these tests behind a custom pytest target if they are integration tests relying on online resources?

I will disable these tests for the time being.

**Comment by frostming** [comment]
They do need submodules: `git submodule update --init`

**Comment by dvzrv** [comment]
That is not possible when building from an sdist tarball. Those tests should be skipped if they can not use a submodule.

**Comment by dvzrv** [comment]
Hi, this is unfortunately still an issue with the sdist tarball for 1.3.1:

```
Cloning into '/tmp/pythonfinder-24oqysfu-test/home/pythonfinder/.asdf'...
fatal: not a git repository: /build/python-pythonfinder/src/pythonfinder-1.3.1/tests/test_artifacts/asdf/../../../.git/modules/tests/test_artifacts/asdf
fatal: Could not read from remote repository.
```
