### ISSUE TITLE
--find cli option only accepts bool

### ISSUE THREAD

**Issue by jmtaysom** [sarugaku/pythonfinder#117]
Using version 1.2.9 on Ubuntu I tried to use `pyfinder --find` but it requires the input to be a bool but throws an error `AttributeError: 'bool' object has no attribute 'strip'`. I would expect to be able to pass in `3.10` into this option and have it identify the location.

**Comment by frostming** [comment]
`pyfinder --find` does require a **version string** and it works fine:

```
❯ pyfinder --find 3.10
Searching for python: 3.10
Found python at the following locations:
python3: 3.10.2 (None) @ /Users/fming/wkspace/github/pythonfinder/venv/bin/python3
```

**Comment by jmtaysom** [comment]
```
$ pyfinder --find 3.10
Usage: pyfinder [OPTIONS]
Try 'pyfinder --help' for help.

Error: Invalid value for '--find': '3.10' is not a valid boolean.

$ pyfinder --version
pyfinder, version 1.2.10
```
