### ISSUE TITLE
Possible code improvements for Python >=3.7

### ISSUE THREAD

**Issue by finswimmer** [sarugaku/pythonfinder#133]
Now that `pythonfinder` depends on `packaging>=22.0` it effectively needs at least Python 3.7. This enables the project to make several code improvements that were not possible until now.

This issue keeps track of a couple of PR I prepared. Because they depend on each other, I will only mark one as ready at a time and will rebase the other once the previous PR is accepted and merged.

* #129
* #131 
* #130 
* #132

**Comment by oz123** [comment]
Hi,
I'll be happy to see that work completed. Please 🙏

**Comment by oz123** [comment]
Ofc, I'll merge as soon as I can.

**Comment by oz123** [comment]
Merged #129.

**Comment by finswimmer** [comment]
#131 is ready

**Comment by finswimmer** [comment]
#130 is more or less ready. I wasn't able to convince `setuptools` to include the `py.typed` into the builds. So some help is needed here. (I could easily do this with Poetry ;) )

**Comment by oz123** [comment]
Well, py.typed is expected to be used by developers, which in turn, are expected to be able to clone the code repository ;-).

**Comment by finswimmer** [comment]
> Well, py.typed is expected to be used by developers, which in turn, are expected to be able to clone the code repository ;-).

`mypy` and co needs this file to find the typehints of the package is used by other projects. See https://mypy.readthedocs.io/en/stable/installed_packages.html

#132 is ready
