### ISSUE TITLE
Unable to find pyenv python installations on windows due to invalid path

### ISSUE THREAD

**Issue by ietz** [sarugaku/pythonfinder#150]
The `Finder` is currently unable to find Python versions installed with pyenv-win because it tries to look for them in an incorrect directory. pyenv-win places the installed Python versions in `~/.pyenv/pyenv-win/versions`. On my fresh Windows install using the newest pyenv-win version 3.1.1, for example, the Python 3.11.4 executable can be found at `~/.pyenv/pyenv-win/versions/3.11.4/python.exe`. However, pythonfinder tries to look for versions in `~/.pyenv/pyenv-win/pyenv-win/versions/` with a duplicate `pyenv-win` directory. This is because pyenv-win sets the `PYENV_ROOT` environment variable to `~/.pyenv/pyenv-win` (see the [installation guide](https://github.com/pyenv-win/pyenv-win/blob/1384196982d861b7cd9062bcb7da633c9de0ffc3/docs/installation.md?plain=1#L140) or the [automated installer](https://github.com/pyenv-win/pyenv-win/blob/1384196982d861b7cd9062bcb7da633c9de0ffc3/pyenv-win/install-pyenv-win.ps1#L128)) on top of which [the `set_pyenv_paths` always adds another `pyenv-win` directory](https://github.com/sarugaku/pythonfinder/blob/849d509f619e06bc85c1906869dff3371e1a593f/src/pythonfinder/environment.py#L84C48-L84C48).

I noticed this because I always had to manually specify the full path to the Python executable when using pipenv. I also found [others having the same issue online](https://stackoverflow.com/questions/74833949/pipenv-is-not-able-to-pickup-the-python-versions-from-pyenvpyenv-win) and was wondering if this behaviour was intentional.
```
PS> ~/.pyenv/pyenv-win/versions/3.11.4/python.exe --version
Python 3.11.4
PS> pipenv install numpy --python 3.11
Warning: Python 3.11 was not found on your system...
Would you like us to install CPython 3.11.4 with Pyenv? [Y/n]: n

You can specify specific versions of Python with:
$ pipenv --python path\to\python
```
Removing the additional `pyenv-win` path component made pipenv work flawlessly, automatically picking up all my python installations.

**Comment by Darsstar** [comment]
The workaround I am currently using is as follows:
- turn on Developer Mode ([for creating symlinks without being in an elevated shell](https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/#:~:text=Symlinks%2C%20or%20symbolic%20links%2C%20are,supported%20symlinks%20since%20Windows%20Vista))
- run in CMD:
```cmd
cd %PYENV_ROOT%
mklink /D pyenv-win .
```
