### ISSUE TITLE
Cannot find pyenv if PYENV_ROOT is not set

### ISSUE THREAD

**Issue by jxltom** [sarugaku/pythonfinder#29]
Current default PYENV_ROOT is ```~/.pyenv```. But the ```PATH``` are usually absolute path, such as ```/home/username/.pyenv```.  Then in the following code, ```last_pyenv``` will be None and pyenv will be considered as not installed.

This makes latest pipenv can not find installed pythons by pyenv when using ```pipenv --python some_version```

https://github.com/sarugaku/pythonfinder/blob/master/src/pythonfinder/models/path.py#L130-L133

**Comment by techalchemy** [comment]
Ah yeah that is right. I thought about that but we just have people set the variable. I guess that’s not always true...
