### ISSUE TITLE
[very small] Sarugaku's main description has a spelling error

### ISSUE THREAD

**Issue by ragegage** [sarugaku/pythonfinder#39]
I know this isn't the right place for this, but it seemed the most apropos.

On [the sarugaku page](https://github.com/sarugaku), it says, "Collection of communnity-driven dependency management projects. Not an authority"; in that sentence "communnity" should be changed to "community".

**Comment by techalchemy** [comment]
oh boy, thanks! that annoys me now too!

**Comment by techalchemy** [comment]
fixed!
