### ISSUE TITLE
Pipenv Pythonfinder error

### ISSUE THREAD

**Issue by ns11** [sarugaku/pythonfinder#58]
Hi,

Look like Pipenv has an issue due to pythonfinder?

https://github.com/pypa/pipenv/issues/3439#issue-398594817

**Comment by jxltom** [comment]
There is a big refactor in pythonfinder but is not released to pipenv yet. It's very likely this issue could be resolved after vendored pythonfinder is updated in pipenv.

**Comment by techalchemy** [comment]
This is most likely resolved as mentioned, in the middle of pushing the updates to pipenv master & you can let me know there if it still isn't fixed
