### ISSUE TITLE
setup.py using unicode without declaring coding

### ISSUE THREAD

**Issue by jayvdb** [sarugaku/pythonfinder#62]
Hi, I am currently packaging all dependencies of pipenv, and encountered a few packages by @sarugaku and @kennethreitz where the setup.py uses the unicode `…`, in messages to be emitted to the user, but the setup.py doesnt including a coding declaration of utf8.  As a result, python spits the dummy and wont run setup.py.

It looks like templated code, possibly `invoke` which seems regularly used in this family of packages, so the core problem might be upstream.

**Comment by jayvdb** [comment]
Another one at https://github.com/pypa/pipenv/blob/master/tests/pytest-pypi/setup.py

**Comment by techalchemy** [comment]
seems likely that it is part of one of kenneth's templates indeed
