### ISSUE TITLE
ValueError by setting multiple versions on pyenv

### ISSUE THREAD

**Issue by EbiEbiEvidence** [sarugaku/pythonfinder#70]
### The issue

First, when I used it with pyenv, i got the below error.
```
  File "/Users/EbiEbiEvidence/.anyenv/envs/pyenv/versions/3.7.3/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/models/python.py", line 117, in get_version_order
    version_paths.remove(version)
ValueError: list.remove(x): x not in list
```

Second, I checked variables around lines the error occurred.

https://github.com/sarugaku/pythonfinder/blob/master/src/pythonfinder/models/python.py#L108-L122

Finally, I found that `version_order` has duplicate versions.
`version_order`: 
[PosixPath('/Users/EbiEbiEvidence/.anyenv/envs/pyenv/versions/3.7.3'), PosixPath('/Users/EbiEbiEvidence/.anyenv/envs/pyenv/versions/2.7.16'), PosixPath('/Users/EbiEbiEvidence/.anyenv/envs/pyenv/versions/3.7.3')]

This is caused by [common pyenv configuration](https://github.com/pyenv/pyenv#choosing-the-python-version) such as the below
```
$ pyenv global 3.7.3 2.7.16 3.7.3
```

**Comment by EbiEbiEvidence** [comment]
See also: https://github.com/pypa/pipenv/pull/3729

**Comment by techalchemy** [comment]
ah yep i can definitely replicate this

thanks for the fix!
