### ISSUE TITLE
AttributeError: 'str' object has no attribute 'isnumeric'

### ISSUE THREAD

**Issue by uranusjr** [sarugaku/pythonfinder#9]
Fixed in 3ccc0a057ea27e2f1da0a3bd48b5e286067ea847, the method is calls `isdigit` (Python is weird). I want to make sure CI passes before adding the news fragment.

**Comment by techalchemy** [comment]
I hate that api. It is super unintuitive

**Comment by uranusjr** [comment]
I’m sure it is the most intuitive design if you’re Dutch.
